[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "boto3>=1.43.36",
    "celery[redis]>=5.6.3",
    "clerk-backend-api>=5.0.7",
    "deepagents>=0.0.5",
    "en-core-web-lg @ https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl",
    "fastapi>=0.136.3",
    "guardrails-ai-detect-pii>=0.0.6",
    "guardrails-ai-prompt-injection-detector",
    "guardrails-ai-toxic-language>=0.0.2",
    "guardrails-ai[api]==0.10.2",
    "gunicorn>=26.0.0",
    "jupyter>=1.1.1",
    "langchain==1.3.14",
    "langchain-community==0.4.2",
    "langchain-mcp-adapters==0.3.0",
    "langchain-openai==1.3.5",
    "langchain-tavily>=0.2.18",
    "langgraph>=1.0.1",
    "mcp>=1.28,<2",
    "notebook>=7.6.1",
    "python-dotenv>=1.2.2",
    "scrapingbee>=2.0.2",
    "supabase>=2.30.1",
    "unstructured[all-docs]==0.18.11",
    "uvicorn>=0.48.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
